name: Build
description: Build

runs:
  using: "composite"
  steps:
    - uses: ./.github/workflows/actions/prepare
    - name: Build dokka
      shell: bash
      run: ./gradlew :dokkaGenerate
    - uses: actions/upload-artifact@v7
      with:
        name: oidc-dokka
        path: build/dokka/html/
        retention-days: 1