name: 'Test Report'
on:
  workflow_run:
    workflows: ['Build Snapshot']                     # runs after CI workflow
    types:
      - completed
permissions:
  contents: read
  actions: read
  checks: write
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Report JVM Tests
        uses: dorny/test-reporter@v2.0.0
        if: success() || failure()    # run this step even if previous step failed
        with:
          artifact: test-results-android            # artifact name
          name: JVM Tests
          path: '*/build/test-results/*jvm*/TEST-*.xml'    # Path to test results
          reporter: java-junit        # Format of test results
      - name: Report iOS Tests
        uses: dorny/test-reporter@v2.0.0
        if: success() || failure()    # run this step even if previous step failed
        with:
          artifact: test-results-ios            # artifact name
          name: iOS Tests            # Name of the check run which will be created
          path: '*/build/test-results/*ios*/TEST-*.xml'    # Path to test results
          reporter: java-junit        # Format of test results